// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcQxzygkW3jnEwMtogZRP6obPWXOFnsCs',
    appId: '1:366569795847:web:46b3d562c0e8e2603915a2',
    messagingSenderId: '366569795847',
    projectId: 'ngobrolin-app',
    authDomain: 'ngobrolin-app.firebaseapp.com',
    storageBucket: 'ngobrolin-app.firebasestorage.app',
    measurementId: 'G-VJM665BPTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOECDmiHCMJjLNGHuSt5Xt82Lc6ORU5g0',
    appId: '1:366569795847:android:7ee01f7cf12438ae3915a2',
    messagingSenderId: '366569795847',
    projectId: 'ngobrolin-app',
    storageBucket: 'ngobrolin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2Mhkkuv1kUWNkeDc1TskA0SPuyD7sus',
    appId: '1:366569795847:ios:10b12bded21b55b23915a2',
    messagingSenderId: '366569795847',
    projectId: 'ngobrolin-app',
    storageBucket: 'ngobrolin-app.firebasestorage.app',
    iosBundleId: 'com.example.ngobrolinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2Mhkkuv1kUWNkeDc1TskA0SPuyD7sus',
    appId: '1:366569795847:ios:10b12bded21b55b23915a2',
    messagingSenderId: '366569795847',
    projectId: 'ngobrolin-app',
    storageBucket: 'ngobrolin-app.firebasestorage.app',
    iosBundleId: 'com.example.ngobrolinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcQxzygkW3jnEwMtogZRP6obPWXOFnsCs',
    appId: '1:366569795847:web:aad082091b419ae63915a2',
    messagingSenderId: '366569795847',
    projectId: 'ngobrolin-app',
    authDomain: 'ngobrolin-app.firebaseapp.com',
    storageBucket: 'ngobrolin-app.firebasestorage.app',
    measurementId: 'G-HMHJMH32F3',
  );
}
